# SPDX-FileCopyrightText: 2026 Masatoshi Nishiguchi
#
# SPDX-License-Identifier: Apache-2.0

# This file is generated by scripts/sync_lgfx_protocol_doc.exs.
# Edit lgfx_port/include_internal/lgfx_port/ops.def instead.

defmodule AtomLGFX.Generated do
  @moduledoc false

  @ops [
    ping: [
      opcode: 0,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :any,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    get_caps: [
      opcode: 1,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :any,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    get_last_error: [
      opcode: 2,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :any,
      capability: :last_error,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    width: [
      opcode: 3,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    height: [
      opcode: 4,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    init: [
      opcode: 5,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :any,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    close: [
      opcode: 6,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :any,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    start_write: [
      opcode: 7,
      public: false,
      raw: true,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :requires_init,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    end_write: [
      opcode: 8,
      public: false,
      raw: true,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :requires_init,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    set_rotation: [
      opcode: 9,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :requires_init,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    set_brightness: [
      opcode: 10,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :requires_init,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    set_color_depth: [
      opcode: 11,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    set_swap_bytes: [
      opcode: 12,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    display: [
      opcode: 13,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: true
    ],
    fill_screen: [
      opcode: 14,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    clear: [
      opcode: 15,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_pixel: [
      opcode: 16,
      public: true,
      raw: false,
      arg_range: 3..3,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_fast_vline: [
      opcode: 17,
      public: true,
      raw: false,
      arg_range: 4..4,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_fast_hline: [
      opcode: 18,
      public: true,
      raw: false,
      arg_range: 4..4,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_line: [
      opcode: 19,
      public: true,
      raw: false,
      arg_range: 5..5,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_rect: [
      opcode: 20,
      public: true,
      raw: false,
      arg_range: 5..5,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    fill_rect: [
      opcode: 21,
      public: true,
      raw: false,
      arg_range: 5..5,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_round_rect: [
      opcode: 22,
      public: true,
      raw: false,
      arg_range: 6..6,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    fill_round_rect: [
      opcode: 23,
      public: true,
      raw: false,
      arg_range: 6..6,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_circle: [
      opcode: 24,
      public: true,
      raw: false,
      arg_range: 4..4,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    fill_circle: [
      opcode: 25,
      public: true,
      raw: false,
      arg_range: 4..4,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_ellipse: [
      opcode: 26,
      public: true,
      raw: false,
      arg_range: 5..5,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    fill_ellipse: [
      opcode: 27,
      public: true,
      raw: false,
      arg_range: 5..5,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_arc: [
      opcode: 28,
      public: true,
      raw: false,
      arg_range: 7..7,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    fill_arc: [
      opcode: 29,
      public: true,
      raw: false,
      arg_range: 7..7,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_bezier: [
      opcode: 30,
      public: true,
      raw: false,
      arg_range: 7..9,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_triangle: [
      opcode: 31,
      public: true,
      raw: false,
      arg_range: 7..7,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    fill_triangle: [
      opcode: 32,
      public: true,
      raw: false,
      arg_range: 7..7,
      allowed_flags: 2,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    set_text_size: [
      opcode: 33,
      public: true,
      raw: false,
      arg_range: 1..2,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    set_text_datum: [
      opcode: 34,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    set_text_wrap: [
      opcode: 35,
      public: true,
      raw: false,
      arg_range: 1..2,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    set_text_font_preset: [
      opcode: 36,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    set_text_color: [
      opcode: 37,
      public: true,
      raw: false,
      arg_range: 1..2,
      allowed_flags: 13,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    set_cursor: [
      opcode: 38,
      public: true,
      raw: false,
      arg_range: 2..2,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    get_cursor: [
      opcode: 39,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    draw_string: [
      opcode: 40,
      public: true,
      raw: false,
      arg_range: 3..3,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: true,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    print: [
      opcode: 41,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: true,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    println: [
      opcode: 42,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: true,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    draw_jpg: [
      opcode: 43,
      public: true,
      raw: false,
      arg_range: 3..9,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: false,
      needs_owned_payload: true,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    push_image: [
      opcode: 44,
      public: true,
      raw: false,
      arg_range: 6..6,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: :pushimage,
      batchable: false,
      needs_owned_payload: true,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    set_clip_rect: [
      opcode: 45,
      public: true,
      raw: false,
      arg_range: 4..4,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    clear_clip_rect: [
      opcode: 46,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: nil,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    create_sprite: [
      opcode: 47,
      public: true,
      raw: false,
      arg_range: 2..3,
      allowed_flags: 0,
      target_policy: :sprite_only,
      state_policy: :requires_init,
      capability: :sprite,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    delete_sprite: [
      opcode: 48,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :sprite_only,
      state_policy: :requires_init,
      capability: :sprite,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    create_palette: [
      opcode: 49,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :sprite_only,
      state_policy: :requires_init,
      capability: :palette,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    set_palette_color: [
      opcode: 50,
      public: true,
      raw: false,
      arg_range: 2..2,
      allowed_flags: 0,
      target_policy: :sprite_only,
      state_policy: :requires_init,
      capability: :palette,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    set_pivot: [
      opcode: 51,
      public: true,
      raw: false,
      arg_range: 2..2,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: :sprite,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    push_sprite: [
      opcode: 52,
      public: true,
      raw: false,
      arg_range: 3..4,
      allowed_flags: 16,
      target_policy: :sprite_only,
      state_policy: :requires_init,
      capability: :sprite,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    push_rotate_zoom: [
      opcode: 53,
      public: true,
      raw: false,
      arg_range: 6..7,
      allowed_flags: 16,
      target_policy: :sprite_only,
      state_policy: :requires_init,
      capability: :sprite,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    get_touch: [
      opcode: 54,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :requires_init,
      capability: :touch,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    get_touch_raw: [
      opcode: 55,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :requires_init,
      capability: :touch,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    set_touch_calibrate: [
      opcode: 56,
      public: true,
      raw: false,
      arg_range: 8..8,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :requires_init,
      capability: :touch,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    calibrate_touch: [
      opcode: 57,
      public: true,
      raw: false,
      arg_range: 0..0,
      allowed_flags: 0,
      target_policy: :bad_target,
      state_policy: :requires_init,
      capability: :touch,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ],
    push_rotate_zoom_list: [
      opcode: 58,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 16,
      target_policy: :any,
      state_policy: :requires_init,
      capability: :sprite,
      batchable: true,
      needs_owned_payload: false,
      sync_only: false,
      batch_boundary_sensitive: false
    ],
    submit_binary_batch: [
      opcode: 59,
      public: true,
      raw: false,
      arg_range: 1..1,
      allowed_flags: 0,
      target_policy: :any,
      state_policy: :requires_init,
      capability: :batch,
      batchable: false,
      needs_owned_payload: false,
      sync_only: true,
      batch_boundary_sensitive: false
    ]
  ]

  @ops_by_name Map.new(@ops)
  @names_by_opcode Map.new(@ops, fn {name, meta} -> {Keyword.fetch!(meta, :opcode), name} end)
  def ops, do: @ops

  def meta(name) when is_atom(name) do
    with {:ok, canonical_name} <- canonical_name(name),
         {:ok, meta} <- Map.fetch(@ops_by_name, canonical_name) do
      {:ok, meta}
    else
      :error -> {:error, {:unknown_lgfx_op, name}}
    end
  end

  def opcode(name) when is_atom(name) do
    fetch_meta_value(name, :opcode)
  end

  def opcode!(name) do
    case opcode(name) do
      {:ok, opcode} -> opcode
      {:error, reason} -> raise ArgumentError, "unknown lgfx op: #{inspect(reason)}"
    end
  end

  def name(opcode) when is_integer(opcode) do
    Map.fetch(@names_by_opcode, opcode)
  end

  def canonical_name(name) when is_atom(name) do
    if Map.has_key?(@ops_by_name, name), do: {:ok, name}, else: :error
  end

  def elixir_name(name) when is_atom(name) do
    case canonical_name(name) do
      {:ok, canonical_name} -> {:ok, canonical_name}
      :error -> {:error, {:unknown_lgfx_op, name}}
    end
  end

  def public?(name), do: flag?(name, :public)

  def raw?(name), do: flag?(name, :raw)

  def batchable?(name), do: flag?(name, :batchable)

  def needs_owned_payload?(name), do: flag?(name, :needs_owned_payload)

  def sync_only?(name), do: flag?(name, :sync_only)

  def batch_boundary_sensitive?(name), do: flag?(name, :batch_boundary_sensitive)

  def arg_range(name), do: fetch_meta_value(name, :arg_range)

  def allowed_flags(name), do: fetch_meta_value(name, :allowed_flags)

  def target_policy(name), do: fetch_meta_value(name, :target_policy)

  def state_policy(name), do: fetch_meta_value(name, :state_policy)

  def capability(name), do: fetch_meta_value(name, :capability)

  defp fetch_meta_value(name, key) when is_atom(name) and is_atom(key) do
    with {:ok, meta} <- meta(name) do
      {:ok, Keyword.fetch!(meta, key)}
    end
  end

  defp flag?(name, flag) when is_atom(name) do
    with {:ok, meta} <- meta(name) do
      Keyword.fetch!(meta, flag)
    else
      {:error, _reason} -> false
    end
  end
end
